### ISSUE TITLE
i know nothing about how to do this

### ISSUE THREAD

**Issue by CASUALMUSH** [rootshellz/Beatporter#12]
can some please help me run this - this is exactly what i need - i have been doing it all one by one for days now - i would really really appreciate if someone could help me with a simpler step by step - this is my first time trying something like this - my email is mike5lowry@yahoo.com

**Comment by rootshellz** [comment]
Mike,

This project takes a bit of work and technical know-how to get working, but I think these steps should set you on the right path.  Basically, you will need to install python and some related packages required by this project; download a copy of this project to your local machine and make some configuration tweaks; set up a Spotify app (similar to creating an account, but in this case for this application to use, instead of a human); and then use python to run the code from this project.  You will run this project every time you want to make updates to your playlists, for example once daily.

At a high level these steps are:
- [Install Python 3](https://realpython.com/installing-python/) and [pip](https://packaging.python.org/tutorials/installing-packages/)
  - Python is used to run the code in this project
  - pip is a component of Python that helps install additional prerequisite code needed by this project
- Once pip is [installed and working](https://packaging.python.org/tutorials/installing-packages/#id13), run `pip install spotipy beautifulsoup4` to install the required packages.
- [Clone this repository](https://docs.github.com/en/repositories/creating-and-managing-repositories/cloning-a-repository) or just [download the ZIP](https://github.com/rootshellz/Beatporter/archive/refs/heads/master.zip) file from the repo.
- [Set up Spotify app](https://developer.spotify.com/documentation/general/guides/app-settings/)
- [Configure the local script (this project / "app")](https://github.com/rootshellz/Beatporter#configuration)
- [Run this script (python "app")](https://github.com/rootshellz/Beatporter#running)
  - The first time you run the code, you will need to [set up authentication](https://github.com/rootshellz/Beatporter#authentication).
    - This is effectively logging the app in to your Spotify account so it can manage your playlists.  This is completely local authentication, similar to how logging in to Spotify in the browser or Spotify app only works on your computer.
  - All subsequent runs of this app will update your playlists based on the configuration you set up above.
    - I run this daily to update all of my playlists.  There are ways to automate this, like using [cron](https://en.wikipedia.org/wiki/Cron) on Linux or Mac or using [task scheduler](https://towardsdatascience.com/automate-your-python-scripts-with-task-scheduler-661d0a40b279) on Windows.
