### ISSUE TITLE
Genres have Changed

### ISSUE THREAD

**Issue by benjaminlewandowski** [rootshellz/Beatporter#4]
Beatport added "Organic House / Downtempo" as a new genre, renamed Electronica / Downtempo" to just "Electronica" and removed "Hardcore / Hard Techno" some while ago. I already updated the config.example.py and opened a pull request.

**Comment by rootshellz** [comment]
Sorry, I've neglected this for too long.  I'll start doing better formal PRs since I just noticed other have used this project.

Genre fixes are now in master:
https://github.com/rootshellz/Beatporter/commit/cadeb7d61a1dfb4aff206d790a38bbdf194071ef
https://github.com/rootshellz/Beatporter/commit/377c605b77f0a00d6196dcd303dba41cea08f7f0
